import type {Metadata} from "next";

export const metadata: Metadata = {
  title: "About",
  description: "Generated by create next app",
};

export default function About() {
  return (
    <div className="flex flex-col flex-1 items-center justify-center bg-zinc-50 font-sans dark:bg-black">
    About
    </div>
  );
}
