import {Metadata} from "next";
import AddVideoScreen from "@/screen/AddVideoScreen/AddVideoScreen";

export const metadata: Metadata = {
    title: "Add Video",
    description: "Generated by create next app",
};

export default async function Home() {


  return (
      <div className="flex flex-col flex-1 items-center justify-center bg-zinc-50 font-sans dark:bg-black">
       <AddVideoScreen/>
      </div>
  );
}