import {Metadata} from "next";
import BooksItems from "@/widgets/BooksItem/BooksItem";
import {Suspense} from "react";

export const metadata: Metadata = {
    title: "all Books page",
    description: "Generated by create books page",
};
export const dynamic = 'force-dynamic';

export default async function Home() {
    const data =await fetch('https://jsonplaceholder.typicode.com/todos')

    const result:Promise<{title:string}[]> = data.json();

  return (
    <div className="flex flex-col flex-1 items-center justify-center bg-zinc-50 font-sans dark:bg-black">
        <Suspense fallback={<>Loading....</>}>
            <BooksItems result={result}/>

        </Suspense>

    </div>
  );
}
