import {Metadata} from "next";
import BooksItems from "@/widgets/BooksItem/BooksItem";
import {Suspense} from "react";


export const metadata: Metadata = {
    title: "all Books page",
    description: "Generated by create books page",
};
export const dynamic = 'force-static';
export const revalidate = 15

export default async function Home() {

    const arr = await fetch("http://localhost:3000/api/title")
    const todoList = await arr.json()
  return (
    <div className="flex flex-col flex-1 items-center justify-center bg-zinc-50 font-sans dark:bg-black">
        <Suspense fallback={<>Loading....</>}>
            <BooksItems result={todoList}/>

        </Suspense>

    </div>
  );
}
