import {Metadata} from "next";
import {LoginForm} from "@/features/auth/ui/LoginForm/LoginForm";

export const metadata: Metadata = {
    title: "Add Video",
    description: "Generated by create next app",
};

export default async function Login() {


  return (
      <div className="flex flex-col flex-1 items-center justify-center bg-zinc-50 font-sans dark:bg-black">
       <LoginForm/>
      </div>
  );
}