import type {Metadata} from "next";

export const metadata: Metadata = {
    title: "Main",
    description: "Generated by create next app",
};

export default function Home() {
  return (
    <div className="flex flex-col flex-1 items-center justify-center bg-zinc-50 font-sans dark:bg-black">
     Main
    </div>
  );
}
