import Image from "next/image";
import AddVideoScreen from "@/screen/AddVideoScreen/AddVideoScreen";
import {Metadata} from "next";

// Определяем интерфейс для params
interface HomeParams {
  params: {
    // Укажите здесь поля, которые ожидаете получить
      videoID?: string;
    // или другие поля
  };
}
export const metadata: Metadata = {
    title: "Add Video",
    description: "Generated by create next app",
};

export default async function Home({ params }: HomeParams) {
  const video_data = await params;
  console.log("video_data", video_data);

  return (
      <div className="flex flex-col flex-1 items-center justify-center bg-zinc-50 font-sans dark:bg-black">
       <AddVideoScreen/>
      </div>
  );
}