import type { Metadata } from "next";
import cl from "./layout.module.css"


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"

    >
      <body className={cl.body_cl} >

      {children}</body>
    </html>
  );
}
