import type {Metadata} from "next";
import {ReactNode} from "react";

export const metadata: Metadata = {
    title: "Contact",
    description: "Generated by create next app",
};

export default function MainClient({children}: {children: ReactNode}) {
    return (
        <div className="flex flex-col flex-1 items-center justify-center bg-zinc-50 font-sans dark:bg-black">
            MainClient
            {children}
        </div>
    );
}
